// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZ_ZzZOszgVib8AlC1QDUD7-ACywWCQo',
    appId: '1:378052541805:web:7eb0b36542b7a4d2312e64',
    messagingSenderId: '378052541805',
    projectId: 'simple-chat-2f130',
    authDomain: 'simple-chat-2f130.firebaseapp.com',
    storageBucket: 'simple-chat-2f130.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6MDGxMgimy6vs_xU4DvHt_Jq7slLBBf8',
    appId: '1:378052541805:android:123a487b840a7e98312e64',
    messagingSenderId: '378052541805',
    projectId: 'simple-chat-2f130',
    storageBucket: 'simple-chat-2f130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRy1On_W6E3oU9dV7R9-IdTA-soy38xJ8',
    appId: '1:378052541805:ios:2f6598044305e946312e64',
    messagingSenderId: '378052541805',
    projectId: 'simple-chat-2f130',
    storageBucket: 'simple-chat-2f130.appspot.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRy1On_W6E3oU9dV7R9-IdTA-soy38xJ8',
    appId: '1:378052541805:ios:2f6598044305e946312e64',
    messagingSenderId: '378052541805',
    projectId: 'simple-chat-2f130',
    storageBucket: 'simple-chat-2f130.appspot.com',
    iosBundleId: 'com.example.simpleChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqZ_ZzZOszgVib8AlC1QDUD7-ACywWCQo',
    appId: '1:378052541805:web:7fa1b8a9a736669f312e64',
    messagingSenderId: '378052541805',
    projectId: 'simple-chat-2f130',
    authDomain: 'simple-chat-2f130.firebaseapp.com',
    storageBucket: 'simple-chat-2f130.appspot.com',
  );

}